# Generated by Django 5.0.3 on 2024-03-31 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('birthday', models.DateField()),
                ('subject', models.CharField(choices=[('Python', 'Python'), ('Django', 'Django'), ('Flask', 'Flask'), ('Java', 'Java'), ('C++', 'C++'), ('C#', 'C#'), ('JavaScript', 'JavaScript')], max_length=50)),
                ('roll', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
            ],
        ),
    ]
